//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

public class Euler2 {
	
	static boolean isEven(int n) {
		if(n % 2 == 0)
			return true;
		else
			return false;
	}
	
	static void fibonacciSequence() {
		int sum = 0;
		int a = 0;
		int b = 1;
		int c = a + b;
		while (c<4000000) {
			if(isEven(c)) {
				sum += c;
			}
			a = b;
			b = c;
			c = a + b;
		}
		System.out.println(sum);
	}

	public static void main(String[] args) {
		
		fibonacciSequence();

	}

}
